### ISSUE TITLE
Yahoo Finance Crumb

### ISSUE THREAD

**Issue by dph10** [Lenskiy/Yahoo-Quandl-Market-Data-Donwloader#3]
Hi, I have been using your getMarketDataViaYahoo function for several months now and it had been working reliably.  This week I started having issues with the function for certain ticker symbols such as: ILTB, MUR, CLDR, VBR, VOOG, just to name a few.  About 80% of the symbols I check work fine, but some symbols (such as those listed above) will no longer work, though they are valid assets at yahoo finance.

 I think the problem is occurring somewhere around lines 71-79 where your code is trying to extract the crumb value.  It is not finding a valid location of the regexp looking for the crumb, and I get the error from line 76.

Are you or anyone else experiencing similar issues, or can you confirm if you have a problem with your function with the symbols I listed above?  Thanks!  I am using Matlab 2020a.

**Comment by Lenskiy** [comment]
Thanks for pointing this out. Yahoo does not require to have the crumb value anymore. 

Now the code will continue even if the value is missing. I've checked on a  couple of tickers and it seems to work.

**Comment by dph10** [comment]
This issue was fixed summer 2020.
